-- Normalize Arabic text in the FTS5 index so diacritic/alef/taa
-- variants match at query time. The REPLACE chains mirror
-- normalizeArabic() in src/lib/server/arabic.ts exactly; arabic.spec.ts
-- asserts this file stays in sync with that generator. Rebuilds the index.
DROP TRIGGER IF EXISTS `store_product_fts_ai`;--> statement-breakpoint
DROP TRIGGER IF EXISTS `store_product_fts_ad`;--> statement-breakpoint
DROP TRIGGER IF EXISTS `store_product_fts_au`;--> statement-breakpoint
CREATE TRIGGER `store_product_fts_ai` AFTER INSERT ON `store_product` BEGIN
  INSERT INTO `store_product_fts`(product_id, name, description, name_en, description_en)
  VALUES (new.id, REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(new.name, 'ى', 'ي'), 'ة', 'ه'), 'ٱ', 'ا'), 'آ', 'ا'), 'إ', 'ا'), 'أ', 'ا'), 'ٰ', ''), 'ـ', ''), 'ٕ', ''), 'ٔ', ''), 'ٓ', ''), 'ْ', ''), 'ّ', ''), 'ِ', ''), 'ُ', ''), 'َ', ''), 'ٍ', ''), 'ٌ', ''), 'ً', ''), REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(new.description, 'ى', 'ي'), 'ة', 'ه'), 'ٱ', 'ا'), 'آ', 'ا'), 'إ', 'ا'), 'أ', 'ا'), 'ٰ', ''), 'ـ', ''), 'ٕ', ''), 'ٔ', ''), 'ٓ', ''), 'ْ', ''), 'ّ', ''), 'ِ', ''), 'ُ', ''), 'َ', ''), 'ٍ', ''), 'ٌ', ''), 'ً', ''), REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(new.name_en, 'ى', 'ي'), 'ة', 'ه'), 'ٱ', 'ا'), 'آ', 'ا'), 'إ', 'ا'), 'أ', 'ا'), 'ٰ', ''), 'ـ', ''), 'ٕ', ''), 'ٔ', ''), 'ٓ', ''), 'ْ', ''), 'ّ', ''), 'ِ', ''), 'ُ', ''), 'َ', ''), 'ٍ', ''), 'ٌ', ''), 'ً', ''), REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(new.description_en, 'ى', 'ي'), 'ة', 'ه'), 'ٱ', 'ا'), 'آ', 'ا'), 'إ', 'ا'), 'أ', 'ا'), 'ٰ', ''), 'ـ', ''), 'ٕ', ''), 'ٔ', ''), 'ٓ', ''), 'ْ', ''), 'ّ', ''), 'ِ', ''), 'ُ', ''), 'َ', ''), 'ٍ', ''), 'ٌ', ''), 'ً', ''));
END;--> statement-breakpoint
CREATE TRIGGER `store_product_fts_ad` AFTER DELETE ON `store_product` BEGIN
  DELETE FROM `store_product_fts` WHERE product_id = old.id;
END;--> statement-breakpoint
CREATE TRIGGER `store_product_fts_au` AFTER UPDATE ON `store_product` BEGIN
  DELETE FROM `store_product_fts` WHERE product_id = old.id;
  INSERT INTO `store_product_fts`(product_id, name, description, name_en, description_en)
  VALUES (new.id, REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(new.name, 'ى', 'ي'), 'ة', 'ه'), 'ٱ', 'ا'), 'آ', 'ا'), 'إ', 'ا'), 'أ', 'ا'), 'ٰ', ''), 'ـ', ''), 'ٕ', ''), 'ٔ', ''), 'ٓ', ''), 'ْ', ''), 'ّ', ''), 'ِ', ''), 'ُ', ''), 'َ', ''), 'ٍ', ''), 'ٌ', ''), 'ً', ''), REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(new.description, 'ى', 'ي'), 'ة', 'ه'), 'ٱ', 'ا'), 'آ', 'ا'), 'إ', 'ا'), 'أ', 'ا'), 'ٰ', ''), 'ـ', ''), 'ٕ', ''), 'ٔ', ''), 'ٓ', ''), 'ْ', ''), 'ّ', ''), 'ِ', ''), 'ُ', ''), 'َ', ''), 'ٍ', ''), 'ٌ', ''), 'ً', ''), REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(new.name_en, 'ى', 'ي'), 'ة', 'ه'), 'ٱ', 'ا'), 'آ', 'ا'), 'إ', 'ا'), 'أ', 'ا'), 'ٰ', ''), 'ـ', ''), 'ٕ', ''), 'ٔ', ''), 'ٓ', ''), 'ْ', ''), 'ّ', ''), 'ِ', ''), 'ُ', ''), 'َ', ''), 'ٍ', ''), 'ٌ', ''), 'ً', ''), REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(new.description_en, 'ى', 'ي'), 'ة', 'ه'), 'ٱ', 'ا'), 'آ', 'ا'), 'إ', 'ا'), 'أ', 'ا'), 'ٰ', ''), 'ـ', ''), 'ٕ', ''), 'ٔ', ''), 'ٓ', ''), 'ْ', ''), 'ّ', ''), 'ِ', ''), 'ُ', ''), 'َ', ''), 'ٍ', ''), 'ٌ', ''), 'ً', ''));
END;--> statement-breakpoint
DELETE FROM `store_product_fts`;--> statement-breakpoint
INSERT INTO `store_product_fts`(product_id, name, description, name_en, description_en)
SELECT id, REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(name, 'ى', 'ي'), 'ة', 'ه'), 'ٱ', 'ا'), 'آ', 'ا'), 'إ', 'ا'), 'أ', 'ا'), 'ٰ', ''), 'ـ', ''), 'ٕ', ''), 'ٔ', ''), 'ٓ', ''), 'ْ', ''), 'ّ', ''), 'ِ', ''), 'ُ', ''), 'َ', ''), 'ٍ', ''), 'ٌ', ''), 'ً', ''), REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(description, 'ى', 'ي'), 'ة', 'ه'), 'ٱ', 'ا'), 'آ', 'ا'), 'إ', 'ا'), 'أ', 'ا'), 'ٰ', ''), 'ـ', ''), 'ٕ', ''), 'ٔ', ''), 'ٓ', ''), 'ْ', ''), 'ّ', ''), 'ِ', ''), 'ُ', ''), 'َ', ''), 'ٍ', ''), 'ٌ', ''), 'ً', ''), REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(name_en, 'ى', 'ي'), 'ة', 'ه'), 'ٱ', 'ا'), 'آ', 'ا'), 'إ', 'ا'), 'أ', 'ا'), 'ٰ', ''), 'ـ', ''), 'ٕ', ''), 'ٔ', ''), 'ٓ', ''), 'ْ', ''), 'ّ', ''), 'ِ', ''), 'ُ', ''), 'َ', ''), 'ٍ', ''), 'ٌ', ''), 'ً', ''), REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(description_en, 'ى', 'ي'), 'ة', 'ه'), 'ٱ', 'ا'), 'آ', 'ا'), 'إ', 'ا'), 'أ', 'ا'), 'ٰ', ''), 'ـ', ''), 'ٕ', ''), 'ٔ', ''), 'ٓ', ''), 'ْ', ''), 'ّ', ''), 'ِ', ''), 'ُ', ''), 'َ', ''), 'ٍ', ''), 'ٌ', ''), 'ً', '') FROM `store_product`;
