// Exports the store catalog from the local libsql database (populated by
// `pnpm run db:reset`) into a plain-SQL seed file for Cloudflare D1. Only the
// store tables are seeded; the FTS5 table fills itself via the triggers on
// store_product. Apply with:
//   wrangler d1 execute beeking --local --file=d1-seed.sql
import { createClient } from "@libsql/client";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

const DB_URL = process.env.DATABASE_URL ?? "file:local.db";
const OUT = resolve(process.argv[2] ?? "d1-seed.sql");

interface Row {
  [key: string]: string | number | null;
}

const client = createClient({ url: DB_URL });

function sqlString(value: string | number | null): string {
  if (value === null) return "NULL";
  if (typeof value === "number") return String(value);
  return `'${value.replace(/'/g, "''")}'`;
}

function toInserts(table: string, columns: string[], rows: Row[]): string[] {
  const colList = columns.join(", ");
  return rows.map((row) => {
    const values = columns.map((c) => sqlString(row[c] ?? null)).join(", ");
    return `INSERT OR IGNORE INTO ${table} (${colList}) VALUES (${values});`;
  });
}

async function main(): Promise<void> {
  const [categories, products, variants, images] = await Promise.all([
    client.execute("SELECT id, name, name_en, slug FROM store_category"),
    client.execute(
      `SELECT id, name, name_en, slug, description, description_en, price, stock, image,
              category_id, featured, created_at FROM store_product`,
    ),
    client.execute(
      `SELECT id, product_id, name, name_en, price, stock, image, sort_order FROM store_product_variant`,
    ),
    client.execute("SELECT id, product_id, url, sort_order FROM store_product_image"),
  ]);

  const lines = [
    "-- Generated by scripts/export-d1-seed.ts — store catalog for Cloudflare D1.",
    "-- Idempotent: INSERT OR IGNORE, safe to re-run.",
    "",
    ...toInserts("store_category", ["id", "name", "name_en", "slug"], categories.rows as Row[]),
    "",
    ...toInserts(
      "store_product",
      [
        "id",
        "name",
        "name_en",
        "slug",
        "description",
        "description_en",
        "price",
        "stock",
        "image",
        "category_id",
        "featured",
        "created_at",
      ],
      products.rows as Row[],
    ),
    "",
    ...toInserts(
      "store_product_variant",
      ["id", "product_id", "name", "name_en", "price", "stock", "image", "sort_order"],
      variants.rows as Row[],
    ),
    "",
    ...toInserts(
      "store_product_image",
      ["id", "product_id", "url", "sort_order"],
      images.rows as Row[],
    ),
    "",
  ];

  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, lines.join("\n"), "utf8");
  console.log(`Wrote ${lines.length} lines to ${OUT}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
