// Exports the store catalog from the local libsql database (populated by
// `pnpm run db:reset`) into a plain-SQL seed file for Cloudflare D1. Only the
// store tables are seeded; the FTS5 table fills itself via the triggers on
// store_product. Apply with:
//   wrangler d1 execute beeking --local --file=d1-seed.sql
//
// FK-safe: rows are merged with INSERT .. ON CONFLICT DO UPDATE (never
// REPLACE, which deletes the old row and violates the store_order_item ->
// store_product foreign key once orders exist), and stale-row deletes skip
// products still referenced by orders so customer history is never orphaned.
import { createClient } from "@libsql/client";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

const DB_URL = process.env.DATABASE_URL ?? "file:local.db";
const OUT = resolve(process.argv[2] ?? "d1-seed.sql");

interface Row {
  [key: string]: string | number | null;
}

const client = createClient({ url: DB_URL });

function sqlString(value: string | number | null): string {
  if (value === null) return "NULL";
  if (typeof value === "number") return String(value);
  return `'${value.replace(/'/g, "''")}'`;
}

function toUpserts(table: string, columns: string[], rows: Row[]): string[] {
  const colList = columns.join(", ");
  const updates = columns
    .filter((c) => c !== "id")
    .map((c) => `${c} = excluded.${c}`)
    .join(", ");
  return rows.map((row) => {
    const values = columns.map((c) => sqlString(row[c] ?? null)).join(", ");
    return `INSERT INTO ${table} (${colList}) VALUES (${values}) ON CONFLICT(id) DO UPDATE SET ${updates};`;
  });
}

function notInList(ids: string[]): string | null {
  if (ids.length === 0) return null;
  return ids.join(", ");
}

async function main(): Promise<void> {
  const [categories, products, variants, images] = await Promise.all([
    client.execute("SELECT id, name, name_en, slug FROM store_category"),
    client.execute(
      `SELECT id, name, name_en, slug, description, description_en, price, stock, image,
              category_id, featured, created_at FROM store_product`,
    ),
    client.execute(
      `SELECT id, product_id, name, name_en, price, stock, image, sort_order FROM store_product_variant`,
    ),
    client.execute("SELECT id, product_id, url, sort_order FROM store_product_image"),
  ]);

  const catSlugs = (categories.rows as Row[]).map((r) => sqlString(r.slug));
  const prodSlugs = (products.rows as Row[]).map((r) => sqlString(r.slug));
  const prodIds = notInList((products.rows as Row[]).map((r) => sqlString(r.id)));
  const variantIds = notInList((variants.rows as Row[]).map((r) => sqlString(r.id)));
  const imageIds = notInList((images.rows as Row[]).map((r) => sqlString(r.id)));

  const staleDeletes = [
    imageIds !== null ? `DELETE FROM store_product_image WHERE id NOT IN (${imageIds});` : null,
    variantIds !== null
      ? `DELETE FROM store_product_variant WHERE id NOT IN (${variantIds});`
      : null,
    // Products referenced by an existing order are kept: deleting them would
    // violate the store_order_item foreign key and orphan customer history.
    prodIds !== null
      ? `DELETE FROM store_product WHERE id NOT IN (${prodIds}) AND id NOT IN (SELECT DISTINCT product_id FROM store_order_item);`
      : null,
    `DELETE FROM store_category WHERE slug NOT IN (${catSlugs.join(", ")}) AND id NOT IN (SELECT DISTINCT category_id FROM store_product);`,
  ].filter((line): line is string => line !== null);

  const lines = [
    "-- Generated by scripts/export-d1-seed.ts — store catalog for Cloudflare D1.",
    "-- Idempotent and FK-safe: upserts merge rows, stale-row deletes skip",
    "-- products still referenced by orders.",
    "",
    ...staleDeletes,
    "",
    ...toUpserts("store_category", ["id", "name", "name_en", "slug"], categories.rows as Row[]),
    "",
    ...toUpserts(
      "store_product",
      [
        "id",
        "name",
        "name_en",
        "slug",
        "description",
        "description_en",
        "price",
        "stock",
        "image",
        "category_id",
        "featured",
        "created_at",
      ],
      products.rows as Row[],
    ),
    "",
    ...toUpserts(
      "store_product_variant",
      ["id", "product_id", "name", "name_en", "price", "stock", "image", "sort_order"],
      variants.rows as Row[],
    ),
    "",
    ...toUpserts(
      "store_product_image",
      ["id", "product_id", "url", "sort_order"],
      images.rows as Row[],
    ),
    `DELETE FROM store_product WHERE slug NOT IN (${prodSlugs.join(", ")}) AND id NOT IN (SELECT DISTINCT product_id FROM store_order_item);`,
    "",
  ];

  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, lines.join("\n"), "utf8");
  console.log(`Wrote ${lines.length} lines to ${OUT}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
